name: Make a request on Render every 14 minutes

on:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  render-request:
    runs-on: ubuntu-latest
    steps:
      - name: Get Products
        run: curl https://medusa-server-w9ik.onrender.com/store/products
